version: 2
# 対象のrequirementsが存在するdirectory分だけ追加
# 現時点でrecursiveに拾う機能はない: https://github.com/dependabot/dependabot-core/issues/3951
updates:
  - package-ecosystem: "pip"
    directory: "/src/trainer01"
    # 頻度・時刻は仮の値
    schedule:
      interval: "daily"
      time: "24:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pip"
    directory: "/src/trainer02"
    schedule:
      interval: "daily"
      time: "24:00"
      timezone: "Asia/Tokyo"